### ISSUE TITLE
Slackのbotでパスワード生成

### ISSUE THREAD

**Issue by noonarai** [kuriume/gtd4k#2]
あんまりこのプロジェクトに関係ないけど、他にリポジトリ作るまでもなかったので。。
slackのライブラリ用に適当なディレクトリ作っておきましょう。

## 要件

mkpwと入力するとパスワードを返す
(kuriumeのslackを使おう)

## 参考

- [Hubotリポジトリ](https://github.com/github/hubot)
- [参考1](http://lab.aratana.jp/entry/2014/12/04/185053)
- [参考2](http://qiita.com/mochidamochiko/items/29c2d77715d8a1ff062a)
- [参考3](http://qiita.com/pekepek/items/b77d173b41f25e3f7c7b)
- [参考4](http://qiita.com/kasaharu/items/1ebff41920f7f71583cd)
- [関連情報1](http://blog.8arrow.org/entry/2016/01/13/183349)

**Comment by Ryutaro0828** [comment]
node.jsのパッケージを管理するnpmでYeomanをインストールします
npm install -g yo grunt-cli bower

**Comment by noonarai** [comment]
@Ryutaro0828 
もうYeomanを使う段階にきたか！
素晴らしい成長速度。

**Comment by Ryutaro0828** [comment]
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/Users/Ryutaro/.nvm/versions/io.js/v2.1.0/bin/bower -> /Users/Ryutaro/.nvm/versions/io.js/v2.1.0/lib/node_modules/bower/bin/bower
/Users/Ryutaro/.nvm/versions/io.js/v2.1.0/bin/grunt -> /Users/Ryutaro/.nvm/versions/io.js/v2.1.0/lib/node_modules/grunt-cli/bin/grunt
/Users/Ryutaro/.nvm/versions/io.js/v2.1.0/bin/yo -> /Users/Ryutaro/.nvm/versions/io.js/v2.1.0/lib/node_modules/yo/lib/cli.js
/Users/Ryutaro/.nvm/versions/io.js/v2.1.0/bin/yo-complete -> /Users/Ryutaro/.nvm/versions/io.js/v2.1.0/lib/node_modules/yo/lib/completion/index.js

> yo@1.8.4 postinstall /Users/Ryutaro/.nvm/versions/io.js/v2.1.0/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✖ Node.js version

Your Node.js version is outdated.
Upgrade to the latest version: https://nodejs.org

✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✖ npm version

Your npm version is outdated.
エラーがでるのでnvmでnode,npmのv2.1.0をinstallします。

**Comment by Ryutaro0828** [comment]
Hubotのジェネレーターをインストールします。
$ npm install -g generator-hubot

次にプロジェクトを作成。
$ mkdir ******
$ cd ******
$ yo hubot

**Comment by noonarai** [comment]
どーだい？？

**Comment by Ryutaro0828** [comment]
$ heroku login
Enter your Heroku credentials.
Email: @mail.address
Password (typing will be hidden): 
Authentication successful.

$ heroku create [your-hubot-app]

**Comment by noonarai** [comment]
@Ryutaro0828 herokuでやることにしたのね。無料プランでいける？

**Comment by Ryutaro0828** [comment]
はい！無料プランでいけそうです！
